targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: flutter_graphql_prototype|lib/schema.graphql

      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: flutter_graphql_prototype|lib/schema.graphql