name: flutter_graphql_prototype
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  ferry: ^0.11.0+1
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  gql_http_link: ^0.4.4+1
  injectable: ^1.5.0

dev_dependencies:
  build_runner: ^2.1.7
  ferry_generator: ^0.6.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.2

flutter:
  uses-material-design: true